"""add provider_payment_id to payments

Revision ID: 3019ab31a795
Revises: 68b9e7c153d2
Create Date: 2026-09-05 20:54:30.716028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3019ab31a795'
down_revision: Union[str, None] = '68b9e7c153d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('provider_payment_id', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'provider_payment_id')
    # ### end Alembic commands ###
